"use client";

import React from "react";
import styles from "./Projects.module.css";
import Slider from "../../Slider/Slider";
import { useSelector, useDispatch } from "react-redux";
import { changeChosenImage, setChosenProject } from "@/redux/projectsSlice";
import { useSwipeable } from "react-swipeable";

import BackIcon from "@/public/assets/icons/BackIcon";
import NextIcon from "@/public/assets/icons/NextIcon";
import GithubIcon from "@/public/assets/icons/GithubIcon";
import { RootState } from "@/redux/store";
import duck from "@/public/assets/images/duck.png";
import capy from "@/public/assets/images/capy.png";

type SliderStylesType = {
  [key: string]: {
    bg: string;
    color: string;
  };
};

const sliderStyles: SliderStylesType = {
  todoGroups: {
    bg: "var(--accent)",
    color: "white",
  },
  moneySpendTracker: {
    bg: "white",
    color: "black",
  },
  getDrunk: {
    bg: "var(--getDrunk-accent-yellow)",
    color: "var(--getDrunk-accent-blue)",
  },
  fastspots: {
    bg: "black",
    color: "white",
  },
};

const Projects = () => {
  const dispatch = useDispatch();
  const { projects, chosenProject, chosenImage } = useSelector(
    (state: RootState) => state.projects
  );

  const projectKeys = Object.keys(projects);

  // Calculate the previous and next project indices
  const currentIndex = projectKeys.indexOf(chosenProject);
  const prevIndex =
    (currentIndex - 1 + projectKeys.length) % projectKeys.length;
  const nextIndex = (currentIndex + 1) % projectKeys.length;

  /**
   * Changes the current project based on the provided index.
   * @param newIndex The index of the project to switch to.
   */
  const handleProjectChange = (newIndex: number) => {
    dispatch(setChosenProject(projectKeys[newIndex]));
  };

  /**
   * Changes the displayed image in the slider.
   * @param value "next" or "previous" indicating the direction.
   */
  const changeImage = (value: "next" | "previous") => {
    dispatch(changeChosenImage(value));
  };

  const swipeHandlers = useSwipeable({
    onSwipedLeft: () => handleProjectChange(nextIndex),
    onSwipedRight: () => handleProjectChange(prevIndex),
    trackMouse: true,
  });

  const lastWheelTimeRef = React.useRef<number>(0);
  const swipeDelay = 1000;

  /**
   * Handles wheel events, typically generated by a touchpad swipe.
   * Only one swipe is processed per swipeDelay duration.
   */
  const handleWheel = (event: React.WheelEvent<HTMLElement>) => {
    const now = Date.now();
    if (now - lastWheelTimeRef.current < swipeDelay) {
      return; // Ignore if within delay period.
    }
    lastWheelTimeRef.current = now;

    // Ensure the gesture is predominantly horizontal.
    if (Math.abs(event.deltaX) > Math.abs(event.deltaY)) {
      if (event.deltaX > 0) {
        handleProjectChange(nextIndex);
      } else if (event.deltaX < 0) {
        handleProjectChange(prevIndex);
      }
    }
  };

  return (
    <section
      {...swipeHandlers}
      onWheel={handleWheel}
      className={styles.projects}
      id="projects"
    >
      <div
        className={`${styles.project} ${
          chosenProject === "todoGroups" ? styles.todoGroups : ""
        } ${chosenProject === "fastspots" ? styles.fastspots : ""} ${
          chosenProject === "getDrunk" ? styles.getDrunk : ""
        } ${
          chosenProject === "moneySpendTracker" ? styles.moneySpendTracker : ""
        }`}
      >
        <button
          className={styles.changeProject}
          onClick={() => handleProjectChange(prevIndex)}
        >
          <BackIcon
            color={
              !["fastspots", "todoGroups"].includes(chosenProject)
                ? "black"
                : "white"
            }
          />
        </button>
        <button
          className={styles.changeProject}
          onClick={() => handleProjectChange(nextIndex)}
        >
          <NextIcon
            color={
              !["fastspots", "todoGroups"].includes(chosenProject)
                ? "black"
                : "white"
            }
          />
        </button>
        <div className={styles.mainContent}>
          <div className={styles.mainContentHeader}>
            <h1>{projects[chosenProject].name}</h1>
            {projects[chosenProject].url && (
              <a href={projects[chosenProject].url} target="blank_">
                Try it out!
              </a>
            )}
          </div>
          <div className={styles.mainContentImage}>
            <button onClick={() => changeImage("previous")}>
              <BackIcon
                color={
                  !["fastspots", "moneySpendTracker"].includes(chosenProject)
                    ? "black"
                    : "white"
                }
              />
            </button>
            <img src={chosenImage} alt={projects[chosenProject].name} />
            <button onClick={() => changeImage("next")}>
              <NextIcon
                color={
                  !["fastspots", "moneySpendTracker"].includes(chosenProject)
                    ? "black"
                    : "white"
                }
              />
            </button>
          </div>
          <div className={styles.projectInfo}>
            <p>{projects[chosenProject].description}</p>
          </div>
        </div>
        <Slider
          items={projects[chosenProject].technologies}
          bg={sliderStyles[chosenProject].bg}
          color={sliderStyles[chosenProject].color}
        />
      </div>

      {chosenProject === "todoGroups" && (
        <>
          <img className={styles.todoGroupsArt} src={duck.src} alt="Duck" />
          <img className={styles.todoGroupsArt} src={capy.src} alt="Capybara" />
        </>
      )}
      <a
        className={`${styles.otherProjects} tooltip`}
        href="https://github.com/xmk0987"
        target="blank_"
      >
        <GithubIcon color="black" size="40px" />
        <span className="tooltiptext">Check out my projects.</span>
      </a>
    </section>
  );
};

export default Projects;
